[package]
name = "dp-jobs"
edition.workspace = true
version.workspace = true

[dependencies]
dp-core = { path = "../dp-core" }
dp-catalog = { path = "../dp-catalog" }
dp-hash = { path = "../dp-hash" }
dp-metadata = { path = "../dp-metadata" }
dp-thumbs = { path = "../dp-thumbs" }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
walkdir = "2"
futures = "0.3"
tokio-util = "0.7"

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
which = "7"
